/**
 * Example class
**/
class ClassicalGreeting {
    constructor(greeting = "Hello", name = "World") {
        this.greeting = greeting;
        this.name = name;
    }

    greet() {
        return `${this.greeting}, ${this.name}!`;
    }
}

const classyGreeting = new ClassicalGreeting("BHZB", "By BoltsHub Dev team.");
console.log(classyGreeting.greet());
console.log('Loading your Server...')
function sleep(milliseconds) {
  const date = Date.now();
  let currentDate = null;
  do {
    currentDate = Date.now();
  } while (currentDate - date < milliseconds);
}

console.log("Almost there...");
sleep(2000);
console.log("Connected with servers!");
console.log("checking whitelist...")
sleep(2000);
console.log("You are whitelisted!")
console.log("DNS address: N/A")
console.log("Fetching OS...")
sleep(5000);
console.log("Chrome OS")
console.log('-----------')
console.log('grabbing ip address...')
sleep(3000)
console.log('Server Host IP: 176.283.28.293')
console.log('BSSID 8C:3B:AD:CB:45:C2')
console.log('MAC: N/A')
console.log('Finished Connectivity diagnostics...')
sleep(1000)
console.log('Cleaning up tracers...')
sleep(789)
console.log('CLEANED TRACER 354721')
console.log('CLEANED TRACER 728748')
sleep(654)
console.log('Cleaning school Registery...')
console.log('CLEANED REGISTERY FOR 8C:3B:AD:CB:45:C2')
sleep(2)
console.log('CLEANED REGISTERY FOR 8C:3B:AD:CB:45:C2')
sleep(2)
console.log('CLEANED REGISTERY FOR 8C:3B:AD:CB:45:C2')
sleep(2)
console.log('CLEANED REGISTERY FOR 8C:3B:AD:CB:45:C2')
sleep(2)
console.log('CLEANED REGISTERY FOR 8C:3B:AD:CB:45:C2')
sleep(2)
console.log('CLEANED REGISTERY FOR 8C:3B:AD:CB:45:C2')
sleep(2)
console.log('CLEANED REGISTERY FOR 8C:3B:AD:CB:45:C2')
sleep(2)
console.log('CLEANED REGISTERY FOR 8C:3B:AD:CB:45:C2')
sleep(2)
console.log('CLEANED REGISTERY FOR 8C:3B:AD:CB:45:C2')
sleep(2)
console.log('CLEANED REGISTERY FOR 8C:3B:AD:CB:45:C2')
sleep(2)
console.log('CLEANED REGISTERY FOR 8C:3B:AD:CB:45:C2')
sleep(2)
console.log('CLEANED REGISTERY FOR 8C:3B:AD:CB:45:C2')
sleep(2)
console.log('CLEANED REGISTERY FOR 8C:3B:AD:CB:45:C2')
sleep(2)
console.log('CLEANED REGISTERY FOR 8C:3B:AD:CB:45:C2')
sleep(2)
console.log('CLEANED REGISTERY FOR 8C:3B:AD:CB:45:C2')
sleep(2)
console.log('CLEANED REGISTERY FOR 8C:3B:AD:CB:45:C2')
sleep(2)
console.log('CLEANED REGISTERY FOR 8C:3B:AD:CB:45:C2')
sleep(2)
console.log('CLEANED REGISTERY FOR 8C:3B:AD:CB:45:C2')
sleep(2)
console.log('CLEANED REGISTERY FOR 8C:3B:AD:CB:45:C2')
sleep(2)
console.log('CLEANED REGISTERY FOR 8C:3B:AD:CB:45:C2')
sleep(2)
console.log('CLEANED REGISTERY FOR 8C:3B:AD:CB:45:C2')
sleep(2)
console.log('CLEANED REGISTERY FOR 8C:3B:AD:CB:45:C2')
sleep(2)
console.log('CLEANED REGISTERY FOR 8C:3B:AD:CB:45:C2')
sleep(2)
console.log('CLEANED REGISTERY FOR 8C:3B:AD:CB:45:C2')
sleep(2)
console.log('CLEANED REGISTERY FOR 8C:3B:AD:CB:45:C2')
sleep(2)
console.log('CLEANED REGISTERY FOR 8C:3B:AD:CB:45:C2')
sleep(2)
console.log('CLEANED REGISTERY FOR 8C:3B:AD:CB:45:C2')
sleep(2)
console.log('Finished cleaning process.')
console.log('Docking...')
sleep(780)
console.log('Con Cons')
console.log('Con Cons')
console.log('Con Cons')
console.log('Con Cons')
console.log('Con Cons')
console.log('Con Cons')
console.log('Con Cons')
console.log('Con Cons')
console.log('Con Cons')
console.log('Con Cons')
console.log('Con Cons')
console.log('Con Cons')
console.log('Con Cons')
console.log('Con Cons')
console.log('Con Cons')
console.log('Con Cons')
console.log('Con Cons')
console.log('Con Cons')
sleep(4000)
console.log('Docked.')
console.log('adding hosts...')
sleep(2000)
console.log('1')
console.log('2')
console.log('3')
console.log('4')
console.log('5')
console.log('6')
console.log('7')
sleep(990)
console.log('estimated MS: 1283.88MS... Printing.')
sleep(40)
console.log('123.74 MS')
sleep(40)
console.log('374.63 MS')
sleep(40)
console.log('567.98 MS')
sleep(40)
console.log('Script encountered an error, Exiting operation.')
sleep(4000)
console.log('Whitelist check, Status: Success')
console.log('Fetching OS, Status: Success')
console.log('Ip Grab, Status: Success')
console.log('Cleaning tracers, Status: Success')
console.log('School Registery Wipe, Status: Success')
console.log('Docking, Status: Success')
console.log('MS HTTPS spam, Status: Failed')
console.log('...')
sleep(800)
console.log('Loading overall sum...')
sleep(3000)
console.log('Successes: 6, Fails: 1. Error encountered: 000000000x000000002')
console.log('Simplified: Could not send ping to host server.')
console.log('Thanks for using BHZB! Credits:')
console.log('Kieran (Code Designer)')
console.log('C00Lkidd (Bug fixes)')
console.log('BoltsHub Dev team (whitelist system)')
console.log('i worked so damn hard on this code pls pls pls no leak or ur a skid')
sleep(1000)
console.log('also this was mostly made to prove to all the skids who use exstensions on google chrome ( yes you ) that i can code')
sleep(1000)
console.log('UR A SKID!!11!1 >> "stop lieing" << UR A SKID!!11!1')